---
title: "Sentencing Data Exploration"
author: "Ki Hyun"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: html_document
---

```{r setup, include=FALSE, message=FALSE}
library(tidyverse)
library(sf)
library(janitor)
library(ggiraph)
library(knitr)
knitr::opts_chunk$set(echo = FALSE)
```

```{r data_cleaning, include=FALSE}
sentencing <- readRDS("data/hxmisd9919_request.RDS")
```

```{r basic_helpers}
recent.five <- sentencing %>% 
  filter(SENTDATE > "20150000")
```

```{r map_helper}
nc_counties <- st_read(system.file("shape/nc.shp", package = "sf"), 
                       quiet = T) %>% 
  clean_names()

county_code <- nc_counties %>% 
  st_drop_geometry() %>% 
  arrange(name) %>%
  select(name) 
  
county_code$code <- map_chr(0:99, ~ case_when(
    . == 0 ~ "000",
    . < 10 ~ str_c("0", as.character(10 * .)),
    TRUE ~ as.character(10 * .)
  ))

map_summary <- function(x, d){
  v <- county_code %>% 
    filter(name == x) %>% 
    .[["code"]]
  
  d %>% 
    filter(COUNTY == v) %>% 
    summarise(
      "Total Convicted" = as.character(n()),
      "Guilty Pleas" = paste0(round(sum(newdisp == 1)/n() * 100, 2), "%"),
      "Felony Cases" = paste0(round(sum(chrgtype == 1)/n() * 100, 2), "%"),
      "Misdemeanor Cases" = paste0(round(sum(chrgtype == 2)/n() * 100, 2), "%"),
      White = paste0(round(sum(race == "W")/n() * 100, 2), "%"),
      Black = paste0(round(sum(race == "B")/n() * 100, 2), "%"),
      Hispanic = paste0(round(sum(race == "H")/n() * 100, 2), "%"),
      Asian = paste0(round(sum(race == "A")/n() * 100, 2), "%"),
      Other = paste0(round(sum(race %in% c("O", "U", "I"))/n() * 100, 2), "%")
    )
}

tooltip_output <- function(x, d, f){
  temp <- f(x, d)
  
  v <- colnames(temp)
  
  str_c(x, "\n", 
        str_c(map_chr(v, ~ paste0(., ": ", temp[[.]], "\n")), 
              collapse = ""))
}
```

## North Carolina Sentencing Data

```{r all_data_setting}
dataf.1 <- sentencing

# felony
felony.1 <- dataf.1 %>% 
  filter(chrgtype == 1)

# misdemeanor
misdemeanor.1 <- dataf.1 %>% 
  filter(chrgtype == 2)

# durham data
durham.1 <- dataf.1 %>% 
  filter(COUNTY == "310")
```

```{r all_general_map}
nc_counties$descript <- nc_counties %>% 
  st_drop_geometry() %>% 
  .[["name"]] %>% 
  sapply(., tooltip_output, d = dataf.1, f = map_summary)

p_1 <- ggplot(nc_counties, aes(fill = name)) +
  geom_sf_interactive(aes(tooltip = descript), show.legend = FALSE) +
  labs(subtitle = "1999 - 2019") +
  theme_void(base_size = 14)

girafe(ggobj = p_1)
```

```{r recent_data_setting}
dataf.2 <- recent.five

# felony
felony.2 <- dataf.2 %>% 
  filter(chrgtype == 1)

# misdemeanor
misdemeanor.2 <- dataf.2 %>% 
  filter(chrgtype == 2)

# durham data
durham.2 <- dataf.2 %>% 
  filter(COUNTY == "310")
```

```{r recent_general_map}
nc_counties$descript <- nc_counties %>% 
  st_drop_geometry() %>% 
  .[["name"]] %>% 
  sapply(., tooltip_output, d = dataf.2, f = map_summary)

p_2 <- ggplot(nc_counties, aes(fill = name)) +
  geom_sf_interactive(aes(tooltip = descript), show.legend = FALSE) +
  labs(subtitle = "2015 - 2019") +
  theme_void(base_size = 14)

girafe(ggobj = p_2)
```

```{r chi_sq_setting}
by_county_chi <- function(county, a, b){
  code <- county_code %>% 
    filter(name == county) %>% 
    .[[2]]
  
  a <- a %>% 
    filter(County == county) %>% 
    select(-1)
  
  b <- b %>% 
    filter(COUNTY == code) %>% 
    select(-1)
  
  chi_sq <- (a$White - b$White)^2 + (a$Asian-b$Asian)^2 + (a$Black-b$Black)^2 + 
    (a$Native - b$Native)^2
  
  tibble(county = county, chi_sq = chi_sq)
}

chi_sq_builder <- function(year){
  pop1 <- readRDS(str_c("data/population/", year, ".RDS")) 
  colnames(pop1) <- c(colnames(pop1)[1], "Native", "Asian", "Black", "Two", 
                      "White", "Total")
  pop_s <- pop1 %>% 
    mutate(
      White = White / Total,
      Asian = Asian / Total,
      Black = Black / Total,
      Native = Native / Total
    ) %>% 
    select(County, White, Asian, Black, Native)
  
  sent_s <- sentencing %>% 
    filter(substr(SENTDATE, 1, 4) == as.character(year)) %>% 
    group_by(COUNTY) %>% 
    summarise(
      White = sum(race == "W")/n(),
      Asian = sum(race == "A")/n(),
      Black = sum(race == "B")/n(),
      Native = sum(race == "I")/n()
    ) %>% 
    ungroup()
  
  map_df(county_code[[1]], by_county_chi, a = pop_s, b = sent_s)
}

```

```{r chi_sq_2000}
chi.sq.a <- chi_sq_builder(2000)

nc_counties.a <- nc_counties %>% 
    arrange(name) %>% 
    mutate(chi.sq = chi.sq.a[[2]],
         descript = str_c(name, "\n p-value: ", round(pchisq(chi.sq, 3), 
                                                      digits = 3)))

p_chi <- ggplot(nc_counties.a, aes(fill = chi.sq)) +
    geom_sf_interactive(aes(tooltip = descript), show.legend = FALSE) +
    scale_fill_gradient(high = "#ffeda0", low = "#f03b20") +
    labs(title = "Year 2000", 
         subtitle = "Racial Disproportionality in Convictions") +
    theme_void(base_size = 14)

girafe(ggobj = p_chi)
```

```{r chi_sq_2001}
chi.sq.a <- chi_sq_builder(2001)

nc_counties.a <- nc_counties %>% 
    arrange(name) %>% 
    mutate(chi.sq = chi.sq.a[[2]],
         descript = str_c(name, "\n p-value: ", round(pchisq(chi.sq, 3), 
                                                      digits = 3)))

p_chi <- ggplot(nc_counties.a, aes(fill = chi.sq)) +
    geom_sf_interactive(aes(tooltip = descript), show.legend = FALSE) +
    scale_fill_gradient(high = "#ffeda0", low = "#f03b20") +
    labs(title = "Year 2001", 
         subtitle = "Racial Disproportionality in Convictions") +
    theme_void(base_size = 14)

girafe(ggobj = p_chi)
```

```{r chi_sq_2002}
chi.sq.a <- chi_sq_builder(2002)

nc_counties.a <- nc_counties %>% 
    arrange(name) %>% 
    mutate(chi.sq = chi.sq.a[[2]],
         descript = str_c(name, "\n p-value: ", round(pchisq(chi.sq, 3), 
                                                      digits = 3)))

p_chi <- ggplot(nc_counties.a, aes(fill = chi.sq)) +
    geom_sf_interactive(aes(tooltip = descript), show.legend = FALSE) +
    scale_fill_gradient(high = "#ffeda0", low = "#f03b20") +
    labs(title = "Year 2002", 
         subtitle = "Racial Disproportionality in Convictions") +
    theme_void(base_size = 14)

girafe(ggobj = p_chi)
```

```{r chi_sq_2003}
chi.sq.a <- chi_sq_builder(2003)

nc_counties.a <- nc_counties %>% 
    arrange(name) %>% 
    mutate(chi.sq = chi.sq.a[[2]],
         descript = str_c(name, "\n p-value: ", round(pchisq(chi.sq, 3), 
                                                      digits = 3)))

p_chi <- ggplot(nc_counties.a, aes(fill = chi.sq)) +
    geom_sf_interactive(aes(tooltip = descript), show.legend = FALSE) +
    scale_fill_gradient(high = "#ffeda0", low = "#f03b20") +
    labs(title = "Year 2003", 
         subtitle = "Racial Disproportionality in Convictions") +
    theme_void(base_size = 14)

girafe(ggobj = p_chi)
```

```{r chi_sq_2004}
chi.sq.a <- chi_sq_builder(2004)

nc_counties.a <- nc_counties %>% 
    arrange(name) %>% 
    mutate(chi.sq = chi.sq.a[[2]],
         descript = str_c(name, "\n p-value: ", round(pchisq(chi.sq, 3), 
                                                      digits = 3)))

p_chi <- ggplot(nc_counties.a, aes(fill = chi.sq)) +
    geom_sf_interactive(aes(tooltip = descript), show.legend = FALSE) +
    scale_fill_gradient(high = "#ffeda0", low = "#f03b20") +
    labs(title = "Year 2004", 
         subtitle = "Racial Disproportionality in Convictions") +
    theme_void(base_size = 14)

girafe(ggobj = p_chi)
```

```{r chi_sq_2005}
chi.sq.a <- chi_sq_builder(2005)

nc_counties.a <- nc_counties %>% 
    arrange(name) %>% 
    mutate(chi.sq = chi.sq.a[[2]],
         descript = str_c(name, "\n p-value: ", round(pchisq(chi.sq, 3), 
                                                      digits = 3)))

p_chi <- ggplot(nc_counties.a, aes(fill = chi.sq)) +
    geom_sf_interactive(aes(tooltip = descript), show.legend = FALSE) +
    scale_fill_gradient(high = "#ffeda0", low = "#f03b20") +
    labs(title = "Year 2005", 
         subtitle = "Racial Disproportionality in Convictions") +
    theme_void(base_size = 14)

girafe(ggobj = p_chi)
```

```{r chi_sq_2006}
chi.sq.a <- chi_sq_builder(2006)

nc_counties.a <- nc_counties %>% 
    arrange(name) %>% 
    mutate(chi.sq = chi.sq.a[[2]],
         descript = str_c(name, "\n p-value: ", round(pchisq(chi.sq, 3), 
                                                      digits = 3)))

p_chi <- ggplot(nc_counties.a, aes(fill = chi.sq)) +
    geom_sf_interactive(aes(tooltip = descript), show.legend = FALSE) +
    scale_fill_gradient(high = "#ffeda0", low = "#f03b20") +
    labs(title = "Year 2006", 
         subtitle = "Racial Disproportionality in Convictions") +
    theme_void(base_size = 14)

girafe(ggobj = p_chi)
```

```{r chi_sq_2007}
chi.sq.a <- chi_sq_builder(2007)

nc_counties.a <- nc_counties %>% 
    arrange(name) %>% 
    mutate(chi.sq = chi.sq.a[[2]],
         descript = str_c(name, "\n p-value: ", round(pchisq(chi.sq, 3), 
                                                      digits = 3)))

p_chi <- ggplot(nc_counties.a, aes(fill = chi.sq)) +
    geom_sf_interactive(aes(tooltip = descript), show.legend = FALSE) +
    scale_fill_gradient(high = "#ffeda0", low = "#f03b20") +
    labs(title = "Year 2007", 
         subtitle = "Racial Disproportionality in Convictions") +
    theme_void(base_size = 14)

girafe(ggobj = p_chi)
```

```{r chi_sq_2008}
chi.sq.a <- chi_sq_builder(2008)

nc_counties.a <- nc_counties %>% 
    arrange(name) %>% 
    mutate(chi.sq = chi.sq.a[[2]],
         descript = str_c(name, "\n p-value: ", round(pchisq(chi.sq, 3), 
                                                      digits = 3)))

p_chi <- ggplot(nc_counties.a, aes(fill = chi.sq)) +
    geom_sf_interactive(aes(tooltip = descript), show.legend = FALSE) +
    scale_fill_gradient(high = "#ffeda0", low = "#f03b20") +
    labs(title = "Year 2008", 
         subtitle = "Racial Disproportionality in Convictions") +
    theme_void(base_size = 14)

girafe(ggobj = p_chi)
```

```{r chi_sq_2009}
chi.sq.a <- chi_sq_builder(2009)

nc_counties.a <- nc_counties %>% 
    arrange(name) %>% 
    mutate(chi.sq = chi.sq.a[[2]],
         descript = str_c(name, "\n p-value: ", round(pchisq(chi.sq, 3), 
                                                      digits = 3)))

p_chi <- ggplot(nc_counties.a, aes(fill = chi.sq)) +
    geom_sf_interactive(aes(tooltip = descript), show.legend = FALSE) +
    scale_fill_gradient(high = "#ffeda0", low = "#f03b20") +
    labs(title = "Year 2009", 
         subtitle = "Racial Disproportionality in Convictions") +
    theme_void(base_size = 14)

girafe(ggobj = p_chi)
```